### ISSUE TITLE
TASK: Switch to  phpcsstandards/php_codesniffer

### ISSUE THREAD

**Issue by grebaldi** [PackageFactory/atomic-fusion-presentationobjects#29]
`squizlabs/php_codesniffer` has been abandoned in favor of `phpcsstandards/php_codesniffer`, see:
https://github.com/squizlabs/PHP_CodeSniffer/issues/3932

also:
https://packagist.org/packages/phpcsstandards/php_codesniffer

**Comment by jrfnl** [comment]
Thank you for your support and your enthousiasm embracing the take-over of the PHP_CodeSniffer package.

In contrast to earlier information, arrangements are now being made to allow the package to continue under its original name on Packagist. The commit (in the new repo) to rename the package [has been reverted](https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/135).

Sorry for the confusion and thank you for understanding. I hope you'll enjoy the 3.8.0 release, which I expect to release this Friday.

**Comment by grebaldi** [comment]
Hi @jrfnl,

thanks a lot for reaching out and taking care :)
